### PR TITLE
Rustler 0.29, Lingua 1.5.0

### PR DESCRIPTION
**Pull request by SteffenDE**

### CODE REVIEW

**Comment by joshrotenberg** [comment]
Thanks! Looks like I need to update the workflow a bit. Once it passes I can merge this.

**Comment by SteffenDE** [comment]
I also experimented with setting up rustler_precompiled here: https://github.com/joshrotenberg/lingua_ex/commit/87b08fc5d7aa2803915d6597dfbcd5e9dcab39f2

For that the automated release to hex should probably be changed though: https://hexdocs.pm/rustler_precompiled/precompilation_guide.html#generating-a-checksum-file

**Comment by joshrotenberg** [comment]
When you get a chance merge in the updates I made to the workflow and see if this passes now. I had super old versions in there.

**Comment by SteffenDE** [comment]
> When you get a chance merge in the updates I made to the workflow and see if this passes now. I had super old versions in there.

done!

**Review by joshrotenberg — APPROVED** [review]
cool

**Pull request merged**
